Fixed up janino issue described by Greg Gardner:
Not sure that this is the right forum to mention technical issues, but here goes anyway.

I'm using your maven repository for cascading which is quite helpful. You have a dependency in your pom.xml for janino 2.5.10 when cascading requires janino 2.5.16. (You have a comment in the pom.xml that you are doing this purposely since there isn't a newer janino in the maven central repository).

However, if you use janino 2.5.10 and try to use the ExpressionFilter in cascading 1.1.1, you will get this Exception:

Caused by: java.lang.NoSuchMethodError: org.codehaus.janino.ExpressionEvaluator.guessParameterNames(Lorg/codehaus/janino/Scanner;)[Ljava/lang/String;

However, if you update the groupId to the current version (org.codehaus.janino instead of janino) version 2.5.16 does exist in the central maven repository:


org.codehaus.janino
janino
2.5.16


And then you won't get exceptions thrown because of the wrong janino version.